# @format

services:
   cooking-api:
      container_name: cooking-front
      restart: always
      image: node:20.10.0
      ports:
         - "4008:3200"
      environment:
         - PORT=3000
      volumes:
         - ./:/usr/src/cooking-front
      working_dir: /usr/src/cooking-front
      networks:
         - monorepo-network

      # FOR PRODUCTION
      command: bash -c "yarn && yarn run build && yarn run start"

networks:
   monorepo-network:
      driver: bridge
